# Generated by Django 3.1.7 on 2021-03-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LAUSERS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120, verbose_name='User-Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Emails')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Event Name')),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('location', models.CharField(max_length=120, verbose_name='Event Location')),
                ('description', models.TextField(verbose_name='Event Description')),
                ('attending', models.ManyToManyField(blank=True, to='events.LAUSERS')),
            ],
        ),
    ]
