# Generated by Django 3.1.7 on 2021-03-28 21:37

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Video name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='video',
            field=embed_video.fields.EmbedVideoField(verbose_name='myVideo'),
        ),
    ]
