# Generated by Django 3.1.7 on 2021-03-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210329_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attending',
        ),
        migrations.AlterField(
            model_name='event',
            name='flyer',
            field=models.ImageField(blank=True, upload_to='staticfiles/flyers'),
        ),
        migrations.DeleteModel(
            name='LAUSERS',
        ),
    ]
