# Generated by Django 3.1.7 on 2021-03-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20210329_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='flyer',
            field=models.ImageField(blank=True, upload_to='media/flyers'),
        ),
    ]
