# Generated by Django 3.1.7 on 2021-03-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20210329_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Event Name')),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Event Location')),
                ('description', models.TextField(verbose_name='Event Description')),
                ('fbLink', models.URLField(blank=True, verbose_name='FB Link')),
            ],
        ),
    ]
