# Generated by Django 3.1.7 on 2021-03-29 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_formevents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormEvents',
            new_name='FormEvent',
        ),
    ]
