# Generated by Django 3.1.7 on 2021-03-30 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_mostrecentvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mostrecentvideo',
            old_name='url',
            new_name='Vid_url',
        ),
    ]
