# Generated by Django 3.1.7 on 2021-03-30 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20210329_2200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.RenameField(
            model_name='mostrecentvideo',
            old_name='Vid_url',
            new_name='vidlink',
        ),
    ]
