# Generated by Django 3.1.7 on 2021-03-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20210329_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='formevent',
            name='flyerLink',
            field=models.URLField(blank=True, verbose_name='FlyerLink'),
        ),
        migrations.AddField(
            model_name='mostrecentvideo',
            name='name',
            field=models.CharField(default='', max_length=120, verbose_name='Vid Name'),
        ),
    ]
