# Generated by Django 3.1.7 on 2021-03-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20210330_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Post Title')),
                ('author', models.CharField(max_length=120, verbose_name='Author')),
                ('subtitle', models.CharField(blank=True, max_length=120, verbose_name='Sub Title')),
                ('cover', models.ImageField(upload_to='', verbose_name='Cover Art')),
                ('body', models.TextField(verbose_name='Body')),
                ('videoLink', models.URLField(verbose_name='Video Link')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
