# Generated by Django 3.1.7 on 2021-04-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='MusicForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Artist Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Artist Email')),
                ('release_date', models.DateTimeField(verbose_name='Release Date')),
                ('link', models.URLField(blank=True, verbose_name='Music Link')),
                ('description', models.TextField(blank=True, verbose_name='Descripton')),
            ],
        ),
    ]
