# Generated by Django 3.1.7 on 2021-04-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_remove_blogpost_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='published',
            field=models.BooleanField(default=False, verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='cover',
            field=models.ImageField(upload_to='media/blog-Covers', verbose_name='Cover Art'),
        ),
    ]
