# Generated by Django 3.1.7 on 2021-04-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20210409_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='1', max_length=120, verbose_name='Category'),
        ),
    ]
