# Generated by Django 3.1.7 on 2021-04-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20210415_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='musicLinks',
            field=models.URLField(blank=True, verbose_name='Bandcamp Link'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fbLink',
            field=models.URLField(blank=True, verbose_name='Social Media Link'),
        ),
    ]
