# Generated by Django 3.1.7 on 2021-04-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20210416_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='musicLinks',
            field=models.TextField(blank=True, verbose_name='Bandcamp Link'),
        ),
    ]
