# Generated by Django 3.1.7 on 2021-04-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20210416_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='audiusLink',
            field=models.URLField(default=False, verbose_name='Audius URL'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='bandcampLink',
            field=models.URLField(default=False, verbose_name='Bandcamp URL'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='favSongTitle',
            field=models.CharField(default='Gummy Bear Song', max_length=120, verbose_name='Favorite Song'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='favSongUrl',
            field=models.URLField(default='www.', max_length=120, verbose_name='Song URL'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='instaLink',
            field=models.URLField(default=False, verbose_name='Insta URL'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='relatedArtist',
            field=models.CharField(default='The Strokes', max_length=120, verbose_name='Similar Artists'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='soundcloudLink',
            field=models.URLField(default=False, verbose_name='Soundcloud URL'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='twitterLink',
            field=models.URLField(default=False, verbose_name='Twitter URL'),
        ),
    ]
