# Generated by Django 3.1.7 on 2021-04-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20210417_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='audiusLink',
            field=models.URLField(blank=True, verbose_name='Audius URL'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='bandcampLink',
            field=models.URLField(blank=True, verbose_name='Bandcamp URL'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='instaLink',
            field=models.URLField(blank=True, verbose_name='Insta URL'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='soundcloudLink',
            field=models.URLField(blank=True, verbose_name='Soundcloud URL'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='twitterLink',
            field=models.URLField(blank=True, verbose_name='Twitter URL'),
        ),
    ]
