# Generated by Django 3.1.7 on 2021-04-19 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_favsongs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='favSongTitle2',
            field=models.CharField(blank=True, max_length=120, verbose_name='Favorite Song 2'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='favSongTitle3',
            field=models.CharField(blank=True, max_length=120, verbose_name='Favorite Song'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='favSongUrl2',
            field=models.URLField(default='www.', max_length=120, verbose_name='Song URL 2'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='favSongUrl3',
            field=models.URLField(default='www.', max_length=120, verbose_name='Song URL 3'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='favSongTitle',
            field=models.CharField(blank=True, max_length=120, verbose_name='Favorite Song 1'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='favSongUrl',
            field=models.URLField(default='www.', max_length=120, verbose_name='Song URL 1'),
        ),
        migrations.AlterField(
            model_name='favsongs',
            name='songtag',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.blogpost'),
        ),
    ]
