# Generated by Django 3.1.7 on 2021-04-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_auto_20210419_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('music', models.URLField(verbose_name='Music')),
            ],
        ),
    ]
