# Generated by Django 3.1.7 on 2021-04-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_discord'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='page',
            field=models.CharField(default='Band-Name', max_length=120, verbose_name='Post ID'),
        ),
    ]
