# Generated by Django 3.1.7 on 2021-04-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_blogpost_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exclusive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Post Title')),
                ('cover', models.ImageField(upload_to='media/blog-Covers', verbose_name='Cover Art')),
                ('body', models.TextField(verbose_name='Body')),
                ('interviewer', models.TextField(verbose_name='Interviewer')),
                ('videoLink', models.URLField(verbose_name='Video Link')),
                ('favSongTitle', models.CharField(blank=True, max_length=120, verbose_name='Favorite Song 1')),
                ('favSongUrl', models.URLField(blank=True, max_length=120, verbose_name='Song URL 1')),
                ('favSongTitle2', models.CharField(blank=True, max_length=120, verbose_name='Favorite Song 2')),
                ('favSongUrl2', models.URLField(blank=True, max_length=120, verbose_name='Song URL 2')),
                ('favSongTitle3', models.CharField(blank=True, default=', ', max_length=120, verbose_name='Favorite Song')),
                ('favSongUrl3', models.URLField(blank=True, default=', ', max_length=120, verbose_name='Song URL 3')),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('published', models.BooleanField(default=False, verbose_name='published')),
            ],
        ),
    ]
