# Generated by Django 3.1.7 on 2021-04-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_exclusive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exclusive',
            old_name='title',
            new_name='name',
        ),
    ]
